import{a as p,S as g,i as d}from"./assets/vendor-UJd43qMQ.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function l(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function o(e){if(e.ep)return;e.ep=!0;const a=l(e);fetch(e.href,a)}})();p.defaults.baseURL="https://pixabay.com";const u=async(t,s,l=1)=>(await p.get("/api/",{params:{key:"50853777-8fecba6f69a77bb52efd7171d",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:s,page:l}})).data,m=({tags:t,largeImageURL:s,webformatURL:l,likes:o,views:e,comments:a,downloads:i})=>`
    <li class="gallery-item">
        <a href="${s}" class="gallery-link">
            <img src="${l}" alt="${t}" width="360" height="200" class="gallery-image">
        </a>
        <div class="gallery-item-stats">
            <p class="gallery-item-description"><span class="gallery-item-property">Views</span><br>${e}</p>
            <p class="gallery-item-description"><span class="gallery-item-property">Likes</span><br>${o}</p>
            <p class="gallery-item-description"><span class="gallery-item-property">Comments</span><br>${a}</p>
            <p class="gallery-item-description"><span class="gallery-item-property">Downloads</span><br>${i}</p>
        </div>
    </li>
  `,r={gallery:document.querySelector(".gallery"),loader:document.querySelector(".js-loader"),searchForm:document.querySelector(".form"),searchBtn:document.querySelector(".search-button"),loadBtn:document.querySelector(".load-button"),searchInput:document.querySelector(".search-input")},c=15;var y=new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});r.searchForm.addEventListener("submit",t=>{t.preventDefault()});r.searchBtn.addEventListener("click",()=>{if(r.loadBtn.classList.remove("active"),n=2,r.searchInput.value.trim())r.gallery.innerHTML="",r.loader.classList.add("active"),u(r.searchInput.value,c).then(t=>{if(t.total===0){d.warning({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const s=t.hits.map(l=>m(l)).join("");r.gallery.innerHTML=s,y.refresh(),t.total>=c&&r.loadBtn.classList.add("active")}).catch(t=>{console.log(t)}).finally(()=>{r.loader.classList.remove("active")});else return});var n=2;r.loadBtn.addEventListener("click",()=>{r.loadBtn.classList.remove("active"),r.loader.classList.add("active"),u(r.searchInput.value,c,n).then(t=>{if(t.hits.length===0){d.warning({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n=2;return}else{const s=t.hits.map(l=>m(l)).join("");r.gallery.insertAdjacentHTML("beforeend",s),y.refresh(),n+=1,r.loadBtn.classList.add("active")}}).catch(t=>{console.log(t)}).finally(()=>{r.loader.classList.remove("active")})});
//# sourceMappingURL=index.js.map
